# Generated by Django 5.2.6 on 2025-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jerseys', 'Jerseys'), ('balls', 'Balls'), ('trainers', 'Trainers'), ('protectors', 'Protectors'), ('clearance', 'Clearance'), ('misc', 'Misc / Others')], max_length=100),
        ),
    ]
